### ISSUE TITLE
Service stops if i "Force Stop" app from settings

### ISSUE THREAD

**Issue by phk101** [mindbirth/snap-services#12]
Hello,

As you mentioned "The SnapService will only be killed if all actions were handled and if it's not binded."

I am using binded service to run background task in Android 8.1(Oreo), it works fine until i force stop from setting or remove app from recent task list.

**Comment by mindbirth** [comment]
Hi,

When the app is killed, all of its running components are killed as well.
This is not the case only when you use foreground services.
Otherwise, everything will be terminated if you clear the app from the recent app list or if you force stop it.

**Comment by mindbirth** [comment]
Closing this ticket. This is standard behaviour OS behaviour, no matter if you use services or snap services.
